name: Tests

on:
  push:
    branches:
      - v1
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  test:
    name: Test and lint
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Run golangci-lint (Go ${{ matrix.go }})
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56

      - name: Run Unit tests (Go ${{ matrix.go }})
        run: make test
